"""Rank the published clips by how well the adapter transcribes them.

For choosing demo material. The browser caps input at 15 seconds, decodes
greedily with a repetition penalty and an n-gram block, and stops at 110
tokens, so this mirrors those settings rather than the benchmark's. A clip that
scores well here is one that will behave in front of an audience.

Weights are the PyTorch adapter, not the int8 ONNX the browser downloads, so
absolute numbers will differ slightly. The ordering is what matters.

    python scripts/rank_clips.py
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import soundfile as sf  # noqa: E402
import torch  # noqa: E402
from transformers import WhisperForConditionalGeneration, WhisperProcessor  # noqa: E402

from homespun.metrics import normalise, score  # noqa: E402

BASE = "openai/whisper-small"
CLIPS = Path("web/assets/clips")
CHAPTERS = Path("web/data/chapters.json")
MAX_SECONDS = 30      # matches the browser
MAX_TOKENS = 200      # matches the browser


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--adapter", type=Path, default=Path("models/homespun-lora-6ep"))
    ap.add_argument("--out", type=Path, default=Path("reports/clip_ranking.md"))
    args = ap.parse_args()

    story = json.loads(CHAPTERS.read_text(encoding="utf-8"))
    entries = [e for ch in story["chapters"] for e in ch.get("entries", [])
               if e.get("clip")]
    if not entries:
        sys.exit("error: no clips in web/data/chapters.json - run export_web.py")

    from peft import PeftModel

    device = "cuda" if torch.cuda.is_available() else "cpu"
    processor = WhisperProcessor.from_pretrained(BASE)
    model = WhisperForConditionalGeneration.from_pretrained(
        BASE, torch_dtype=torch.float16 if device == "cuda" else torch.float32)
    model = PeftModel.from_pretrained(model, str(args.adapter)).merge_and_unload()
    model = model.to(device).eval()
    forced = processor.get_decoder_prompt_ids(language="hi", task="transcribe")

    rows = []
    for e in entries:
        path = CLIPS / e["clip"]
        if not path.exists():
            continue
        audio, sr = sf.read(str(path), dtype="float32")
        full = len(audio) / sr
        if full > MAX_SECONDS:
            audio = audio[: int(MAX_SECONDS * sr)]

        feats = processor(audio, sampling_rate=sr, return_tensors="pt").input_features
        feats = feats.to(device, model.dtype)
        with torch.inference_mode():
            ids = model.generate(
                feats, forced_decoder_ids=forced, num_beams=5,
                max_new_tokens=MAX_TOKENS,
            )
        hyp = processor.batch_decode(ids, skip_special_tokens=True)[0].strip()

        # The reference covers the whole utterance; a truncated clip can only
        # match its opening, so score the hypothesis against as much of the
        # reference as it could have reached.
        ref = e["quote"]
        if full > MAX_SECONDS:
            keep = max(1, int(len(ref.split()) * MAX_SECONDS / full))
            ref = " ".join(ref.split()[:keep])

        s = score([ref], [hyp])
        rows.append({
            "clip": e["clip"], "utt_id": e["utt_id"],
            "seconds": round(full, 1), "truncated": full > MAX_SECONDS,
            "cer": round(s.cer, 3), "wer": round(s.wer, 3),
            "reference": ref, "hypothesis": hyp,
            "english": e.get("english", ""),
        })

    rows.sort(key=lambda r: r["cer"])

    print(f"{'clip':14} {'sec':>5} {'CER':>6} {'WER':>6}  note")
    for r in rows:
        note = "truncated" if r["truncated"] else ""
        flag = "  <- best" if r is rows[0] else ""
        print(f"{r['clip']:14} {r['seconds']:5.1f} {r['cer']:6.3f} {r['wer']:6.3f}  {note}{flag}")

    lines = ["# Which clips transcribe best", "",
             "Generated by `scripts/rank_clips.py`. Decoded exactly as the browser",
             "does on a GPU: 30 second cap, beam 5, 200 token limit. Sorted by",
             "character error, lowest first.", "",
             "| clip | seconds | CER | WER | |", "|---|---:|---:|---:|---|"]
    for r in rows:
        lines.append(f"| `{r['clip']}` | {r['seconds']} | {r['cer']} | {r['wer']} | "
                     f"{'truncated at 15s' if r['truncated'] else ''} |")
    lines += ["", "## The three best, in full", ""]
    for r in rows[:3]:
        lines += [f"### `{r['clip']}` - CER {r['cer']}", "",
                  f"- said: {r['reference']}",
                  f"- model: {r['hypothesis']}"]
        if r["english"]:
            lines.append(f"- meaning: {r['english']}")
        lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding="utf-8")
    print(f"\n[ok] {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
